scatter:
  jshead:
    - js/d3.v3.js
    - js/d3.tip.v0.6.3.js
  css:
    - css/scatter.css
  cdn:
    jshead:
      - http://d3js.org/d3.v3.js
      - http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js
    css:
      - http://timelyportfolio.github.io/rCharts_jackman/scatter/css/scatter.css
